version: "3"

services:
  mariadb:
    container_name: job_listings_mariadb
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=admin
      - MARIADB_DATABASE=job_listings

  server:
    container_name: job_listings_server
    image: docker.io/bitnami/laravel:9
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=admin
      - DB_DATABASE=job_listings
    volumes:
      - "./server:/app"
    depends_on:
      - mariadb
  phpmyadmin:
    container_name: job_listings_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - MYSQL_USERNAME=admin
      - MYSQL_ROOT_PASSWORD=""
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      #- PMA_USER=admin
      #- PMA_PASSWORD=""
    depends_on:
      - mariadb

  client:
    container_name: job_listings_client
    build:
      context: ./client
    ports:
      - "3000:3000"
